Repository codestates-seb/seb41_main_030, pull requests merged in 2023-01, with the labels that each got.

#3 [feat/nav] reset.css 파일 추가
  client/package-lock.json
  client/public/index.html
  client/src/App.js
  client/src/components/Nav.js
  client/src/index.js
  client/src/reset.css
Labels: FE

#5 [Feat/fe-nav] nav 인터페이스 구현
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Nav.js
  client/src/components/NavModal.js
  client/src/index.js
  client/src/reset.css
Labels: frontend, interface

#6 [feat/fe-footer] footer 인터페이스 구현
  client/src/App.js
  client/src/components/Footer.js
Labels: frontend, interface

#11 [feat/fe-boards] 커뮤니티 게시판 구현
  client/data.json
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.js
  client/src/components/Footer.js
  client/src/components/Nav.js
  client/src/components/NavModal.js
  client/src/components/boards/BoardsHeader.js
  client/src/components/boards/BoardsMain.js
  client/src/pages/Boards.js
  client/src/pages/test.js
Labels: frontend, interface, feat

#13 [feat/fe main] 메인 페이지 구현
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Nav.js
  client/src/components/main/Carousel.js
  client/src/components/main/Preview.js
  client/src/globalStyle.css
  client/src/icons/main-leaf.svg
  client/src/icons/main-page-arrow-left.svg
  client/src/icons/main-page-arrow-right.svg
  client/src/pages/Main.js
Labels: frontend, interface, feat

#19 [feat] 로그인, 회원가입 페이지 구현
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Nav.js
  client/src/pages/ForgotPw.js
  client/src/pages/Login.js
  client/src/pages/Signup.js
Labels: frontend, interface, feat

#20 Feat/fe boards
  client/data.json
  client/src/App.js
  client/src/components/Nav.js
  client/src/components/boards/BoardsMain.js
  client/src/components/boards/CreateBoardHeader.js
  client/src/components/boards/CreateBoardMain.js
  client/src/pages/Boards.js
  client/src/pages/CreateBoard.js
Labels: bugFix, frontend, interface, feat

#29 [feat/fe-mypage] 마이페이지 구현, 메인 페이지 반응형 적용
  client/data.json
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/main/Carousel.js
  client/src/components/main/Preview.js
  client/src/components/mypage/Loader.js
  client/src/components/mypage/MyPageAnswer.js
  client/src/components/mypage/MyPageEdit.js
  client/src/components/mypage/MyPagePosts.js
  client/src/components/mypage/UserPost.js
  client/src/pages/Main.js
  client/src/pages/MyPage.js
Labels: frontend, interface, feat

#31 [Feat/fe-counsel-map] 전문 상담기관 페이지 구현
  client/.gitignore
  client/public/index.html
  client/src/App.js
  client/src/components/Nav.js
  client/src/components/NavModal.js
  client/src/components/map/KakaoMap.js
  client/src/components/map/mapDummy.js
  client/src/icons/map-pin.png
  client/src/pages/BoardDetail.js
  client/src/pages/CounselingCenter.js
Labels: frontend, interface, feat

#38 [Feat/fe boards] 서버 관련 코드 수정 및 리팩토링
  client/data.json
  client/src/components/boards/BoardDetailAnswer.js
  client/src/components/boards/BoardDetailAnswersMain.js
  client/src/components/boards/BoardDetailQuestion.js
  client/src/components/boards/BoardsHeader.js
  client/src/components/boards/BoardsMain.js
  client/src/components/boards/CreateBoardHeader.js
  client/src/components/boards/CreateBoardMain.js
  client/src/components/boards/EditBoardMain.js
  client/src/components/boards/dateCalculation.js
  client/src/pages/BoardDetail.js
  client/src/pages/Boards.js
  client/src/pages/CreateBoard.js
  client/src/pages/EditBoard.js
  client/src/states/answerEditState.js
  client/src/states/index.js
Labels: bugFix, frontend, feat

#41 [Feat/fe boards] AWS 서버 임시 연결
  client/package-lock.json
  client/package.json
  client/src/components/boards/BoardDetailAnswer.js
  client/src/components/boards/BoardDetailAnswersMain.js
  client/src/components/boards/BoardDetailQuestion.js
  client/src/components/boards/CreateBoardMain.js
  client/src/components/boards/EditBoardMain.js
  client/src/setupProxy.js
Labels: bugFix, frontend

#43 [Feat/fe-intro] 소개 페이지 구현
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Nav.js
  client/src/components/intro/IntroBoard.js
  client/src/components/intro/IntroCenter.js
  client/src/components/intro/IntroMain.js
  client/src/components/intro/IntroProfessional.js
  client/src/components/intro/useScrollFadeIn.js
  client/src/icons/intro-bubble.svg
  client/src/icons/intro-tag.svg
  client/src/icons/intro-write.svg
  client/src/pages/Intro.js
Labels: frontend, interface

#45 [Refactor/fe mypage] 마이페이지, 로그인 AWS 서버 임시 연결
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/mypage/MyPageAnswer.js
  client/src/components/mypage/MyPageEdit.js
  client/src/components/mypage/MyPagePosts.js
  client/src/pages/Login.js
  client/src/pages/MyPage.js
  client/src/setupProxy.js
Labels: frontend

#52 [Refactor/fe-mypage-main-login] 메인 페이지, 마이페이지, 로그인 페이지 서버 연결, UI 조정
  client/src/components/Nav.js
  client/src/components/NavModal.js
  client/src/components/main/Carousel.js
  client/src/components/main/Preview.js
  client/src/components/mypage/MyPageAnswer.js
  client/src/components/mypage/MyPageEdit.js
  client/src/components/mypage/MyPagePosts.js
  client/src/components/mypage/UserPost.js
  client/src/pages/Login.js
  client/src/pages/Main.js
  client/src/pages/MyPage.js
Labels: refactor, bugFix, frontend

#53 [feat/fe] 회원가입 모달 및 로그인시 Nav 변경
  client/src/App.js
  client/src/components/Nav.js
  client/src/pages/Login.js
  client/src/pages/Signup.js
Labels: frontend, feat

#55 [feat/fe-boards] 주석처리한 태그 기능 추가, 폰트 변경 및 css 수정
  client/src/components/boards/BoardDetailAnswer.js
  client/src/components/boards/BoardDetailAnswerCreate.js
  client/src/components/boards/BoardDetailQuestion.js
  client/src/components/boards/BoardsHeader.js
  client/src/components/boards/BoardsMain.js
  client/src/components/boards/CreateBoardHeader.js
  client/src/components/boards/CreateBoardMain.js
  client/src/components/boards/EditBoardMain.js
Labels: refactor, frontend

#56 [refator/fe-boards] 태그 미 선택해도 태그가 자리를 차지하는 오류 수정
  client/src/components/boards/BoardDetailQuestion.js
  client/src/components/boards/BoardsMain.js
  client/src/components/boards/EditBoardMain.js
Labels: bugFix, frontend

#58 [Feat/fe self check] 자가진단 결과 페이지 구현 및 css 수정 (반응형 추가)
  client/src/components/map/KakaoMap.js
  client/src/components/self/SelfCheckError.js
  client/src/components/self/SelfCheckHeader.js
  client/src/components/self/SelfCheckMain.js
  client/src/components/self/SelfCheckResultConfirm.js
  client/src/components/self/SelfCheckResultHeader.js
  client/src/components/self/SelfCheckResultMain.js
  client/src/components/self/SelfCheckTable.js
  client/src/components/self/resultConfirm.js
  client/src/components/self/selfCheckDummy.js
  client/src/pages/CounselingCenter.js
Labels: refactor, frontend, feat

#60 [Feat/fe boards] 로그인 상태에 따른 권한 부여 (글 등록, 댓글 등록, 공감) 기능 추가, 로그아웃 임시 추가
  client/src/components/Nav.js
  client/src/components/NavModal.js
  client/src/components/boards/BoardDetailAnswer.js
  client/src/components/boards/BoardDetailAnswerCreate.js
  client/src/components/boards/BoardDetailAnswerList.js
  client/src/components/boards/BoardDetailQuestion.js
  client/src/components/boards/BoardModal.js
  client/src/components/boards/BoardsHeader.js
  client/src/components/boards/CreateBoardMain.js
  client/src/components/boards/EditBoardMain.js
  client/src/components/self/SelfCheckError.js
  client/src/components/self/SelfCheckMain.js
  client/src/pages/BoardDetail.js
  client/src/pages/Boards.js
  client/src/states/index.js
  client/src/states/selfCheckErrorState.js
Labels: refactor, frontend, feat

#61 [refactor/fe-footer] footer, login, singup 페이지 리팩토링
  client/src/components/Footer.js
  client/src/pages/Login.js
  client/src/pages/Signup.js
Labels: refactor, frontend

#62 Feat/fe-intro-mypage-main] 소개페이지 UI조정, 마이페이지 오류 수정, 메인페이지 태그 서버 연결
  client/package-lock.json
  client/package.json
  client/src/components/boards/BoardDetailQuestion.js
  client/src/components/intro/IntroBoard.js
  client/src/components/intro/IntroCenter.js
  client/src/components/intro/IntroMain.js
  client/src/components/intro/IntroProfessional.js
  client/src/components/intro/IntroResponsive.js
  client/src/components/main/Carousel.js
  client/src/components/main/Preview.js
  client/src/components/mypage/MyPageEdit.js
  client/src/icons/intro-center-img.png
  client/src/icons/intro-mobile-center-img.png
  client/src/pages/CounselingCenter.js
  client/src/pages/Intro.js
  client/src/pages/Main.js
  client/src/pages/MyPage.js
  client/src/pages/Signup.js
Labels: bugFix, frontend, interface

#63 [refactor/fe] 필요하지 않은 컴포넌트 삭제 및 url 환경변수관련 설정
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Footer.js
  client/src/components/boards/BoardDetailAnswer.js
  client/src/components/boards/BoardDetailAnswerCreate.js
  client/src/components/boards/BoardDetailQuestion.js
  client/src/components/boards/BoardsMain.js
  client/src/components/boards/CreateBoardMain.js
  client/src/components/boards/EditBoardMain.js
  client/src/components/main/Carousel.js
  client/src/components/mypage/MyPageAnswer.js
  client/src/components/mypage/MyPageEdit.js
  client/src/components/mypage/MyPagePosts.js
  client/src/pages/BoardDetail.js
  client/src/pages/CounselingCenter.js
  client/src/pages/ForgotPw.js
  client/src/pages/Login.js
  client/src/pages/MyPage.js
  client/src/pages/Signup.js
  client/src/setupProxy.js
Labels: refactor, frontend

#64 [Inter/fe-intro] 소개 페이지 목업 이미지 추가, 소개 페이지에 반응형 소개 컴포넌트 추가, UI 조정
  client/src/components/intro/IntroBoard.js
  client/src/components/intro/IntroMain.js
  client/src/components/intro/IntroResponsive.js
  client/src/components/intro/IntroSelfCheck.js
  client/src/components/mypage/MyPageEdit.js
  client/src/components/self/SelfCheckHeader.js
  client/src/components/self/SelfCheckResultConfirm.js
  client/src/components/self/SelfCheckResultHeader.js
  client/src/components/self/SelfCheckResultMain.js
  client/src/icons/intro-board-img.png
  client/src/icons/intro-mobile-responsive-img.png
  client/src/icons/intro-responsive-img.png
  client/src/icons/intro-selfcheck-img.png
  client/src/pages/Intro.js
  client/src/pages/Signup.js
Labels: bugFix, frontend, interface

#66 [feat/fe-counselor]전문가 페이지 제작
  client/src/App.js
  client/src/components/counselor/CounselorList.js
  client/src/components/counselor/CounselorModal.js
  client/src/components/counselor/Counseloritem.js
  client/src/components/counselor/counselorHeader.js
  client/src/icons/Counselor01.png
  client/src/icons/Counselor02.png
  client/src/icons/Counselor03.png
  client/src/icons/Counselor04.png
  client/src/icons/Counselor05.png
  client/src/icons/Counselor06.png
  client/src/pages/Counselor.js
Labels: frontend, feat

#68 [fix/fe-counselor] 파일명 대소문자 변경
  client/src/components/counselor/CounselorHeader.js
Labels: bugFix, frontend

#76 [Refactor/fe boards] 프록시 설정 해제
  client/package.json
  client/public/index.html
  client/src/components/boards/BoardDetailAnswer.js
  client/src/components/boards/BoardDetailAnswerCreate.js
  client/src/components/boards/BoardDetailAnswerList.js
  client/src/components/boards/BoardDetailQuestion.js
  client/src/components/boards/BoardModal.js
  client/src/components/boards/BoardsHeader.js
  client/src/components/boards/BoardsMain.js
  client/src/components/boards/CreateBoardHeader.js
  client/src/components/boards/CreateBoardMain.js
  client/src/components/boards/EditBoardMain.js
  client/src/pages/BoardDetail.js
  client/src/pages/CounselingCenter.js
  client/src/pages/CreateBoard.js
  client/src/pages/EditBoard.js
  client/src/pages/SelfCheckResult.js
  client/src/setupProxy.js
Labels: refactor, frontend

#77 fe branch merge
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.js
  client/src/components/Footer.js
  client/src/components/boards/BoardDetailAnswer.js
  client/src/components/boards/BoardDetailAnswerCreate.js
  client/src/components/boards/BoardDetailAnswerList.js
  client/src/components/boards/BoardDetailQuestion.js
  client/src/components/boards/BoardModal.js
  client/src/components/boards/BoardsHeader.js
  client/src/components/boards/BoardsMain.js
  client/src/components/boards/CreateBoardHeader.js
  client/src/components/boards/CreateBoardMain.js
  client/src/components/boards/EditBoardMain.js
  client/src/components/counselor/CounselorHeader.js
  client/src/components/counselor/CounselorList.js
  client/src/components/counselor/CounselorModal.js
  client/src/components/counselor/Counseloritem.js
  client/src/components/intro/IntroBoard.js
  client/src/components/intro/IntroMain.js
  client/src/components/intro/IntroResponsive.js
  client/src/components/intro/IntroSelfCheck.js
  client/src/components/main/Carousel.js
  client/src/components/mypage/MyPageAnswer.js
  client/src/components/mypage/MyPageEdit.js
  client/src/components/mypage/MyPagePosts.js
  client/src/components/self/SelfCheckHeader.js
  client/src/components/self/SelfCheckResultConfirm.js
  client/src/components/self/SelfCheckResultHeader.js
  client/src/components/self/SelfCheckResultMain.js
  client/src/icons/Counselor01.png
  client/src/icons/Counselor02.png
  client/src/icons/Counselor03.png
  client/src/icons/Counselor04.png
  client/src/icons/Counselor05.png
  client/src/icons/Counselor06.png
  client/src/icons/intro-board-img.png
  client/src/icons/intro-mobile-responsive-img.png
  client/src/icons/intro-responsive-img.png
  client/src/icons/intro-selfcheck-img.png
  client/src/pages/BoardDetail.js
  client/src/pages/CounselingCenter.js
  client/src/pages/Counselor.js
  client/src/pages/CreateBoard.js
  client/src/pages/EditBoard.js
  client/src/pages/ForgotPw.js
  client/src/pages/Intro.js
  client/src/pages/Login.js
  client/src/pages/MyPage.js
  client/src/pages/SelfCheckResult.js
  client/src/pages/Signup.js
  client/src/setupProxy.js
Labels: frontend

#78 [fix] board -> 서버 url 수정
  client/src/components/boards/BoardDetailAnswer.js
  client/src/components/boards/BoardDetailAnswerCreate.js
  client/src/components/boards/BoardDetailQuestion.js
  client/src/components/boards/BoardsMain.js
  client/src/components/boards/CreateBoardMain.js
  client/src/components/boards/EditBoardMain.js
  client/src/pages/BoardDetail.js
Labels: bugFix, frontend

#79 [Refactor/fe boards] 프록시 해제
  client/src/components/boards/BoardDetailAnswer.js
  client/src/components/boards/BoardDetailAnswerCreate.js
  client/src/components/boards/BoardDetailQuestion.js
  client/src/components/boards/BoardsMain.js
  client/src/components/boards/CreateBoardMain.js
  client/src/components/boards/EditBoardMain.js
  client/src/components/main/Carousel.js
  client/src/components/mypage/MyPageAnswer.js
  client/src/components/mypage/MyPageEdit.js
  client/src/components/mypage/MyPagePosts.js
  client/src/pages/BoardDetail.js
  client/src/pages/Login.js
  client/src/pages/MyPage.js
  client/src/pages/Signup.js
Labels: bugFix, frontend

#81 [Inter/fe-responsive] 소개 페이지 UI 조정, favicon 추가
  client/public/favicon.ico
  client/public/index.html
  client/src/components/intro/IntroBoard.js
  client/src/components/intro/IntroCenter.js
  client/src/components/intro/IntroMain.js
  client/src/components/intro/IntroResponsive.js
  client/src/components/intro/IntroSelfCheck.js
Labels: frontend, interface

#84 [Refactor/fe boards] boardmain의 split 오류 수정
  .DS_Store
  client/src/components/boards/BoardCard.js
  client/src/components/boards/BoardDetailQuestion.js
  client/src/components/boards/BoardsMain.js
  client/src/icons/Spinner-1s-200px.gif
  client/src/pages/BoardDetail.js
Labels: bugFix, frontend

#85 [merge] develop 브랜치에 fe 브랜치 merge합니다!
  .DS_Store
  client/src/components/boards/BoardCard.js
  client/src/components/boards/BoardDetailQuestion.js
  client/src/components/boards/BoardsMain.js
  client/src/icons/Spinner-1s-200px.gif
  client/src/pages/BoardDetail.js
Labels: frontend

#86 [Refactor/fe boards] 상세 게시글 빈 태그 보이지 않도록 수정, 게시판 로딩 추가
  client/src/components/boards/BoardDetailQuestion.js
  client/src/components/boards/BoardsMain.js
Labels: refactor, frontend

#88 [Fix/fe-main] 메인 페이지 태그 오류 수정, 마이페이지 작성글,답변 없을 경우 UI 수정, favicon 관련 href 속성 url 주소 추가
  client/public/index.html
  client/src/components/main/Preview.js
  client/src/components/mypage/MyPageAnswer.js
  client/src/components/mypage/MyPagePosts.js
Labels: bugFix, frontend, interface

#90 [Feat/fe boards] tag filter 기능 추가
  client/src/components/boards/BoardsMain.js
  client/src/pages/BoardDetail.js
Labels: refactor, frontend, feat

#93 [Design/fe-mypage-responsive] 마이페이지 게시글,답변 작성하지 않았을 경우 안내 텍스트 반응형 조정
  client/src/components/mypage/MyPageAnswer.js
  client/src/components/mypage/MyPagePosts.js
Labels: frontend, interface

#94 [Feat/fe boards] 게시판 정렬 수정, nav 로그인 상태 수정
  .DS_Store
  client/src/components/Nav.js
  client/src/components/NavModal.js
  client/src/components/boards/BoardsMain.js
Labels: bugFix, frontend

#96 [Fix/fe] 로그인 상태 처리 오류 수정
  client/src/components/boards/BoardDetailAnswer.js
  client/src/components/boards/BoardDetailAnswerCreate.js
  client/src/components/boards/BoardDetailQuestion.js
  client/src/components/boards/BoardsHeader.js
  client/src/pages/Login.js
Labels: bugFix, frontend

#98 [Fix/fe] boardsMain 스크롤 이벤트 삭제, 로딩 컴포넌트 높이 변경
  client/src/components/boards/BoardsMain.js
Labels: bugFix, frontend

#99 [Fix/fe-mypage] 회원탈퇴 시 Nav바 상태가 변하지 않는 오류 수정
  client/src/pages/MyPage.js
Labels: bugFix, frontend

#102 [Fix/fe-main] 메인 페이지 캐러셀 반응형 오류 수정
  client/src/components/main/Carousel.js
Labels: bugFix, frontend

#104 [Fix/fe boards] boardModal, boardMain css 수정 및 리팩토링
  client/src/components/boards/BoardModal.js
  client/src/components/boards/BoardsMain.js
  client/src/pages/BoardDetail.js
  client/src/pages/Boards.js
  client/src/pages/SelfCheckResult.js
Labels: refactor, bugFix, frontend
