Repository codestates-seb/seb41_main_030, pull requests merged in 2023-02, with the labels that each got.

#106 [fix/fe-nav] hover, active 효과 수정 및 추가, 소개 페이지 링크 추가
  client/src/components/Nav.js
  client/src/components/NavModal.js
Labels: refactor, frontend, feat

#107 [fix/fe-boards] 비로그인 상태 고민 작성 페이지 진입막힘 해제
  client/src/components/boards/BoardsHeader.js
  client/src/components/boards/CreateBoardMain.js
  client/src/pages/Boards.js
  client/src/pages/CreateBoard.js
Labels: refactor, frontend

#108 [fix] 메인 클릭시 이전 nav 활성화가 보이는 오류 수정
  client/src/components/Nav.js
  client/src/components/NavModal.js
Labels: bugFix, frontend

#109 [Fix/fe-mainpage] 메인 페이지 헤더에 소개 페이지 이동 버튼 추가, 메인 페이지 반응형 UI 재조정, 전문가 페이지 헤더 UI 조정
  client/src/components/counselor/CounselorHeader.js
  client/src/components/counselor/Counseloritem.js
  client/src/components/intro/IntroResponsive.js
  client/src/components/main/Carousel.js
  client/src/components/main/Preview.js
  client/src/components/mypage/MyPageEdit.js
  client/src/components/mypage/UserPost.js
  client/src/pages/Main.js
  client/src/pages/MyPage.js
Labels: refactor, frontend, interface

#113 [fix/fe-signup] 비밀번호 정규식 수정, 비밀번호 숨김 on,off 기능 추가
  client/src/pages/Login.js
  client/src/pages/Signup.js
Labels: bugFix, frontend, feat

#114 [fix/fe-nav] nav 반응형 수정
  client/src/components/Nav.js
Labels: refactor, frontend

#117 [Refactor/fe-interface] 전체 페이지 헤더 UI 통일, 서버 문제 대비 메인 페이지 더미데이터 추가
  client/src/components/boards/BoardsHeader.js
  client/src/components/boards/CreateBoardHeader.js
  client/src/components/counselor/CounselorHeader.js
  client/src/components/main/Carousel.js
  client/src/components/main/dummyPost.js
  client/src/components/self/SelfCheckHeader.js
Labels: refactor, frontend, interface

#118 [Refactor/fe-interface] 메인 페이지 작성글 없을 경우 더미데이터 표시, 마이페이지 비밀번호 표시 기능, 소개 페이지 반응형 UI 조정
  client/src/components/intro/IntroResponsive.js
  client/src/components/main/Carousel.js
  client/src/components/mypage/MyPageEdit.js
  client/src/data/dummyPost.js
Labels: frontend, interface

#120 [fix/fe-boards] 랜덤 이미지 프로필 추가 및 url 관련 수정
  client/src/components/boards/BoardCard.js
  client/src/components/boards/BoardDetailAnswer.js
  client/src/components/boards/BoardDetailAnswerCreate.js
  client/src/components/boards/BoardDetailAnswerList.js
  client/src/components/boards/BoardDetailQuestion.js
  client/src/components/boards/BoardModal.js
  client/src/components/boards/BoardsMain.js
  client/src/components/boards/CreateBoardMain.js
  client/src/components/boards/EditBoardMain.js
  client/src/components/main/Carousel.js
  client/src/components/self/SelfCheckError.js
  client/src/pages/BoardDetail.js
  client/src/pages/Login.js
  client/src/pages/MyPage.js
  client/src/pages/Signup.js
  client/src/states/index.js
  client/src/states/questionImgState.js
Labels: refactor, frontend, feat

#123 [refactor] memberIdState localStorage -> sessionStorage 변경
  client/src/states/memberIdState.js
Labels: refactor, frontend

#126 [refactor/fe-logout] 로그아웃 API 적용
  client/src/components/Nav.js
  client/src/components/NavModal.js
Labels: refactor, frontend

#128 [Refactor/fe-mypage] url 수정 시 누락된 부분 수정
  client/src/components/mypage/MyPageEdit.js
  client/src/components/mypage/MyPagePosts.js
Labels: refactor, frontend
